# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

font_family      family='JetBrains Mono' style=Medium 
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
disable_ligatures cursor

# cursor_shape block cursor_shape_unfocused hollow cursor_blink_interval -1 cursor_trail 0
cursor_blink_interval 0
cursor_trail 1

# scrollbar scrolled scrollback_lines 2000 scrollback_pager_history_size 0
scrollbar never
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -

enable_audio_bell no
# Not using splits, horizontal and vertical
enabled_layouts fat,tall,grid,stack

# confirm_os_window_close -1 hide_window_decorations no
hide_window_decorations yes
confirm_os_window_close 0

include tabbar.conf
include mappings.conf

# allow_remote_control no update_check_interval 24 clipboard_max_size 512
allow_remote_control yes
update_check_interval 0
# use startup session to avoid starting with a non-session tab
startup_session ./sessions/home.kitty-session
# TODO shell integration
shell_integration enabled, no-cursor
