# Purpose:
# - Reuse some tmux commands( muscle memory )
# - Using kitty_mod with a symbol requires 4 fingers on the ferris sweep keyboard
# - NOTE: tmux has a display window menu prefix < and a pane menu prefix >
# - NOTE: tmux can rotate panes
# - https://tmuxcheatsheet.com/

# kitty_mod ctrl+shift
# clear_all_shortcuts no

# TODO: pressing `prefix + prefix` sends <prefix> to the shell

map ctrl+space>r load_config_file

# Tab commands(tmux windows).
# map ctrl+shift+t
map ctrl+space>c new_tab_with_cwd
# map ctrl+shift+q
map ctrl+space>& close_tab
# map ctrl+shift+right
map ctrl+space>n next_tab
# map ctrl+shift+left
map ctrl+space>p previous_tab
# map ctrl+shift+alt+t
map ctrl+space>, set_tab_title
# map ctrl+shift+l
map ctrl+space>space next_layout
# Keep ctrl+shift+. move_tab_forward and ctrl+shift+, move_tab_backward
#
# Add tab commands
#
# tmux zoom
map ctrl+space>z toggle_layout stack
# tmux last window
map ctrl+space>l goto_tab -1
map ctrl+space>right goto_tab -1
# tmux select window
map ctrl+space>1 goto_tab 1
map ctrl+space>2 goto_tab 2
map ctrl+space>3 goto_tab 3
map ctrl+space>4 goto_tab 4
map ctrl+space>5 goto_tab 5
map ctrl+space>6 goto_tab 6

# Scrolling with symbol layer also requires 4 fingers.
# This is fine as I don't scroll much and use the symbol layer often.
# TODO: understand next and previous shell prompt

# Window commands(tmux panes)
#
# Akin super enter for a new terminal, swap the builtin mappings, use with_cwd
map kitty_mod+enter new_os_window_with_cwd
# TODO: Use s for split?
map kitty_mod+n new_window_with_cwd
# use tmux kill pane instead of kitty_mod+w close_window
map ctrl+space>x close_window
# Not using default next window kitty_mod ]
# Not using default previous window kitty_mod [
# Not using default move window forward kitty_mod f
# Not using default move window backward kitty_mod b
# Not using default move window to top kitty_mod `
# No need for extra arrow mappings to focus neighbour windows
#
# Add window commands
#
# Tmux previously active pane
map ctrl+space>; nth_window -1
# Tmux next pane
map ctrl+space>o next_window
# Tmux display pane numbers
map ctrl+space>q focus_visible_window
map ctrl+space>Q swap_with_window

# Other commands
# TODO: paste from selection and pass selection to program
# Do use input unicode character kitty_mod+u
# Do use open url kitty_mod+e
# Do use open kitty shell kitty_mod+escape
# Keep font mappings, not used often
# Not using toggle full screen and maximize
# Not using kitty.conf and opacity mappings

# Sessions
# Interactively create a session from session files or directories
action_alias sessionizer launch --allow-remote-control --type=overlay kitty_sessionizer_owns
map ctrl+space>h sessionizer
map ctrl+space>left sessionizer
# List active sessions and switch
map ctrl+space>k goto_session
map ctrl+space>up goto_session
# List active sessions to close. Aka tmux detach?
map ctrl+space>d close_session
# Jump to last active session
map ctrl+space>j goto_session -1
map ctrl+space>down goto_session -1

# Testing... Mimic function keys like f1 etc
map ctrl+space>f>1 launch --allow-remote-control kitty +kitten broadcast
