# tab_fade 0.25 0.5 0.75 1 tab_separator " ┇"
tab_bar_edge top
tab_bar_margin_height 2.0 0.0
tab_bar_style separator
# tab_bar_style separator
# tab_powerline_style round
tab_bar_align center
# tab_fade 1 1 1 1
tab_separator " "
# active_tab_font_style   bold-italic
active_tab_font_style   bold
# tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"
tab_title_template " {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{index}:{title} "
tab_bar_filter session:~ or session:^$
